### ISSUE TITLE
应该是依赖版本不对，但不清除具体是要哪个版本

### ISSUE THREAD

**Issue by calonye** [jhj0517/stable-diffusion-webui-Layer-Divider#19]
Layer Divider Extension : applying configs to model..
Traceback (most recent call last):
  File "/home/ubuntu/aigc/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/aigc/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/ubuntu/aigc/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/ubuntu/aigc/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 4457, in postprocess
    file = self.img_array_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "/home/ubuntu/aigc/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 355, in img_array_to_temp_file
    return self.pil_to_temp_file(pil_image, dir, format="png")
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
-------------
环境，
python3.10.10
pip 23.2.1

pytoshop                 1.2.1
Cython                   3.0.0

onnx                     1.13.1
numba                    0.56.4
numpy                    1.23.5

--
SD 1.3.2    torch: 2.0.1+cu118  •  xformers: 0.0.19

**Comment by jhj0517** [comment]
Hi @calonye. 
This looks like bug related with gradio. since gradio has major updates recently, the old version of gradio became problematic in several project, which I've also experienced in other project. 

So using latest gradio would solve this problem, 
You can simply update your SD WebUI to 1.5.1 which is latest version.
I've just tested it, it works fine in latest version of SD WebUI.

**Comment by calonye** [comment]
原来如此，但是我现在不敢更新至1.5.1版本，因为我同时在使用supervisor，以保护webui进程，但是我只要更新webui的版，我的supervisor就无法对webui进程进行保护了，我在github提问过，但是没有人回答我。
这让我很为难
总之，感谢你的建议，当webui再次更新版本时，我再尝试一下。因为supervisor保护webui进程的功能，对我来说很重要。
