### ISSUE TITLE
No such file or directory (mac OS)

### ISSUE THREAD

**Issue by danger-diffusion** [jhj0517/stable-diffusion-webui-Layer-Divider#7]
Hi! Thank you for this great approach. I am eager to try this out, but I am running run into the following issue:

```
Layer Divider Extension : Error while Loading SAM model! [Errno 2] No such file or directory: '/Volumes/Swap/DANGER Diffusion/stable-diffusion-webui/models/sam\\sam_vit_h_4b8939.pth'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Volumes/Swap/DANGER Diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-Layer-Divider/scripts/layer_divider_modules/sam.py", line 68, in generate_mask_app
    self.set_mask_generator()
  File "/Volumes/Swap/DANGER Diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-Layer-Divider/scripts/layer_divider_modules/sam.py", line 42, in set_mask_generator
    self.mask_generator = SamAutomaticMaskGenerator(
  File "/opt/homebrew/lib/python3.10/site-packages/segment_anything/automatic_mask_generator.py", line 123, in __init__
    self.predictor = SamPredictor(model)
  File "/opt/homebrew/lib/python3.10/site-packages/segment_anything/predictor.py", line 31, in __init__
    self.transform = ResizeLongestSide(sam_model.image_encoder.img_size)
AttributeError: 'NoneType' object has no attribute 'image_encoder'
```

Hard coding `model_path` in sam.py (/Volumes/Swap/DANGER Diffusion/stable-diffusion-webui/models/sam/sam_vit_h_4b8939.pth) solves it for the moment. But then I get the same error that is mentioned [here](https://github.com/jhj0517/stable-diffusion-webui-Layer-Divider/issues/5).

**Comment by danger-diffusion** [comment]
Your recent commit solved the path issue for me – thanks a lot!
